* _HTML.H - Header file for _HTML class library.
*

*-- Messages
#DEFINE M_ALIAS_LOC					"Alias"
#DEFINE M_FILE_LOC					"Archivo"
#DEFINE M_GENERATING_HTML_LOC		"Generando HTML"
#DEFINE M_GENHTML_LOC				"GenHTML"
#DEFINE M_NOT_FOUND_LOC				"no se encuentra"
#DEFINE M_NOT_SUPPORTED_LOC			"no se admite"
#DEFINE M_OBJECT_LOC				"Objeto"
#DEFINE M_SAVE_LOC					"Guardar"
#DEFINE M_SAVE_AS_LOC				"Guardar como"

*-- ASCII codes
#DEFINE TAB			CHR(9)
#DEFINE LF			CHR(10)
#DEFINE CR			CHR(13)
#DEFINE CR_LF		CR+LF
#DEFINE	EVAL_ITEM	CHR(0)+"_"+CHR(255)
