* _TABLE2.H

***********************************
* Constants for classes
#DEFINE MB_QUESTIONYESNO	36
#DEFINE MB_ISYES			6

***********************************
* strings for _dialogbutton classes

#DEFINE ERR_NOVCXLIB_LOC 	"No se encontró la biblioteca VCX"
#DEFINE ERR_NOCLASS_LOC		"No se encontró la clase"

***********************************
* strings for _navmenu classes

#DEFINE C_DELREC_LOC	"¿Desea eliminar este registro?"

#DEFINE MENU_TOP_LOC	"\<Superior"
#DEFINE MENU_BOTTOM_LOC	"\<Inferior"
#DEFINE MENU_NEXT_LOC	"\<Siguiente"
#DEFINE MENU_PREV_LOC	"\<Anterior"
#DEFINE MENU_RECORD_LOC	"\<Nº registro..."
#DEFINE MENU_GOTO_LOC	"\<Ir a registro"
#DEFINE MENU_ADD_LOC	"\<Agregar registro"
#DEFINE MENU_DELETE_LOC	"\<Eliminar registro"
#DEFINE MENU_SORT_LOC	"Ordenar datos..."
#DEFINE MENU_FILTER_LOC	"\<Filtro de datos..."
#DEFINE MENU_FILTER2_LOC	"Filtro a\<vanzado..."
#DEFINE ERR_UNIQUEKEY_LOC  "Error de infracción de clave única."
#DEFINE ERR_UNIQUEKEY2_LOC  "¿Desea deshacer los cambios?"

***********************************
* strings for _sortdialog classes

#DEFINE C_NONE_LOC	"Nº registro"
#DEFINE ERR_NOTAGS_LOC	"No hay índices disponibles en esta tabla para ordenar."
#DEFINE C_NONE_LOC	"Record#"

