
****VERIFICANDO DEUDA PENDIENTE****
*WAIT WINDOW "VERIFICANDO DATOS DEL AÑO: "+STR(YEAR(DATE()),4) NOWA
PARAMETERS A
STORE 0 TO TOTCRED,TOTPAGO
SELECT DETACONV
SET FILTER TO FECHA_EMIS<=A
*SET FILTER TO YEAR(FECHA_EMIS)=YEAR(DATE())
SET SAFETY OFF
SELECT PACICONV
SET ORDER TO CUENTA_C
SELECT * FROM PACICONV INTO TABLE C:\SIGEP\TEMP\TPPACICV ORDER BY CUENTA_C
SET SAFETY ON
SELECT TPPACICV
GO TOP
DO WHILE !EOF()
   CODPAC=CUENTA_C
   SELECT DETACONV
   SUM ALL MONTO TO TOTCRED FOR CUENTA_C=CODPAC AND EMPTY(FECHA_CANC)
   SELECT CUOTASCV
   SUM ALL MONTO TO TOTPAGO FOR CUENTA_C=CODPAC AND CTOD("01/"+STR(MES_DCTO,2)+"/"+STR(ANIO_DCTO,4))<=A
   * AND YEAR(FECHA)=YEAR(DATE())
   SELECT RECIBO
   SUM ALL MONTO TO TOTPAGO1 FOR CUENTA_C=CODPAC AND FECHA_EMIS<=A AND TIPO!="A"
   SELECT TPPACICV
   REPLACE DEUDA_PEND WITH DEUDA_INIC+TOTCRED-TOTPAGO-TOTPAGO1
   SKIP
ENDDO
****FILTRA LOS QUE TIENEN SALDO POR ERROR DE REDONDEO****
SELECT tppacicv
REPLACE ALL DEUDA_PEND WITH 0 FOR DEUDA_PEND<=0.02
*********************************************************
SELECT DETACONV
SET FILTER TO
IF A=DATE()
   SELECT TPPACICV
   GO TOP
   DO WHILE !EOF()
      SET RELATION TO CUENTA_C INTO PACICONV
      REPLACE PACICONV.DEUDA_PEND WITH TPPACICV.DEUDA_PEND
      SKIP
   ENDDO
ENDIF

