*- cvtalert.h
*- #INCLUDE file for cvtalert.vcx
*- (c) Microsoft Corporation 1995

#DEFINE C_SELBACKDIR_LOC	"Directorio de seguridad:"
#DEFINE C_SELLOGFILE_LOC	"Nombre del archivo de registro:"
#DEFINE C_SELECT_LOC		"Seleccionar"
#DEFINE C_SELCODEFILE_LOC	"Archivo de código:"
#DEFINE C_CONVERTBOTH_LOC	"\<Convertir registros de formularios de Macintosh y Windows"
#DEFINE C_RETAIN30_LOC		"\<Mantener los valores de las propiedades predeterminadas de FoxPro3.0"

#DEFINE C_CONVERTSCX_LOC	"Archivos \<SCX"
#DEFINE C_CONVERTVCX_LOC	"Archivos \<VCX"
#DEFINE C_RECURSEDIR_LOC	"\<Comprobar subdirectorios"
#DEFINE C_SELSCXFILE_LOC	"Seleccione el archivo que desea actualizar:"
#DEFINE C_SELSCXDIR_LOC		"Seleccione el directorio:"


#DEFINE E_BADFNAME_LOC		"El nombre para el archivo de código no es válido."
#DEFINE E_BADBACKDIR_LOC	"El directorio de copia de seguridad no es válido."
#DEFINE E_BADLOGNAME_LOC	"El nombre para el archivo de registro no es válido."

#DEFINE C_BACKDIR			"OLD"
#DEFINE C_LOGEXT			"LOG"
#DEFINE N_STDMODE			1
#DEFINE N_DEVMODE			2

#DEFINE C_SCREENTYPEPARM	"SCREEN"
#DEFINE C_PROJECTTYPEPARM	"PROJECT"
#DEFINE C_CATALOGTYPEPARM	"CATALOG"
#DEFINE C_REPORTTYPEPARM	"REPORT"
#DEFINE C_MENUTYPEPARM		"MENU"
#DEFINE C_LABELTYPEPARM		"LABEL"
#DEFINE C_DB4QUERYTYPEPARM	"DB4QUERY"
#DEFINE C_DB4FORMTYPEPARM	"DB4FORM"
#DEFINE C_DB4REPORTTYPEPARM	"DB4REPORT"
#DEFINE C_DB4LABELTYPEPARM	"DB4LABEL"
#DEFINE C_DB4VERSIONPARM	"DBASE"
#DEFINE C_FOXVERSIONPARM	"FOX"
#DEFINE C_FMTTYPEPARM		"FORMAT"
#DEFINE C_FPLUSFRXTYPEPARM	"FB+FRX"
