*- FOREIGN.H
*-
*- Header file for Foreign.PRG
*-
*- (c) Microsoft Corporation 1995

#DEFINE E_OPEN_LOC		"Error @1 al abrir "
#DEFINE E_COPY_LOC		"Ocurrió el error @1 al intentar copiar el catálogo a "
#DEFINE E_CREATE_LOC	"Error @1 al crear "
#DEFINE E_NAMEPROB_LOC	"Debido a un conflicto de nombres, el nombre del archivo de catálogo se ha cambiado a "
#DEFINE E_NOFIND_LOC	"No se puede encontrar el archivo migrado @1."

#DEFINE C_CAT2FPC_LOC	"Cambiando la estructura del catálogo..."
#DEFINE C_CONFIRM1_LOC	"Debe convertir su &wzsString antes de poder modificarlo en FoxPro. El @1 original permanecerá sin cambios. ¿Desea continuar con la conversión?"
#DEFINE C_SAVETO_LOC	"Guardar @1 como:"

#DEFINE C_DBASEEOF		CHR(26)		&& code DBase use to mark EOF in .QBE file