*- migdb4.h
*-
*-
#DEFINE lbl_type 11
#DEFINE scr_type 18
#DEFINE frm_type 7

#DEFINE C_ERRDB3FILE	105	&& Not a dBASE IV file.  FoxPro converts dBASE III FRMs and LBLs natively.
#DEFINE C_ERRBADDB4		106	&& Not a DBASE IV file (the file has the wrong header for dBASE IV).

#DEFINE C_ERRFTYPE_LOC	"El tipo de ID de archivo es incorrecto para un archivo .SCR o .LBL de dBASE IV."
#DEFINE C_ERRNOFMT_LOC	"Imposible encontrar el archivo con formato dBASE III (.FMT)."

