*-- (c) Microsoft Corporation 1995

*-- STRINGS.H
*-- Include this file where needed for localization
*-- purposes

*-- Messagebox Titles
#DEFINE ERRORTITLE_LOC      "Se produjo un error"

*-- Toolbar names
#DEFINE TB_FORMDESIGNER_LOC  "Diseñador de formularios"
#DEFINE TB_STANDARD_LOC      "Estándar"
#DEFINE TB_LAYOUT_LOC        "Diseño"
#DEFINE TB_QUERY_LOC		 "Diseñador de consultas"
#DEFINE TB_VIEWDESIGNER_LOC  "Diseñador de vistas"
#DEFINE TB_COLORPALETTE_LOC  "Paleta de colores"
#DEFINE TB_FORMCONTROLS_LOC  "Controles del formulario"
#DEFINE TB_DATADESIGNER_LOC  "Diseñador de bases de datos"
#DEFINE TB_REPODESIGNER_LOC  "Diseñador de informes"
#DEFINE TB_REPOCONTROLS_LOC  "Controles del informe"
#DEFINE TB_PRINTPREVIEW_LOC  "Vista preliminar"
#DEFINE WIN_COMMAND_LOC		 "Comando"			&& Ventana Comando


*-- Messagebox Messages
#DEFINE FILENOTEXIST_LOC	"No existe el archivo:"
#DEFINE BADPASSWORD_LOC		"Contraseña incorrecta. (Consulte el cuadro de texto Sugerencia)"
#DEFINE BADNAME_LOC			"No se encuentra el nombre."
#DEFINE BADUPDATE_LOC		"No se puede actualizar, y volverá al valor original."
#DEFINE SAVECHANGES_LOC		"¿Desea guardar primero los cambios?"
#DEFINE ASKDELETE_LOC		"¿Realmente desea eliminar esta información?"
#DEFINE TAGNOTFOUND_LOC		"No se encuentra la etiqueta del índice."
#DEFINE REPORTNOTFOUND_LOC	"No se encuentra el archivo de informe."
#DEFINE PRINTERNOTREADY_LOC	"La impresora no está lista"
#DEFINE NORECSMATCHED_LOC	"Ningún registro coincide con el criterio."
#DEFINE DELETEREC_LOC		"¿Realmente desea eliminar este registro?"
#DEFINE DELETEWARN_LOC      "Advertencia de eliminación"
#DEFINE NOTHINGTOPRINT_LOC  "No hay nada que imprimir."
#DEFINE PASSWORDEMPTY_LOC	"La nueva contraseña no puede estar en blanco."
#DEFINE PSWDNOTCNFRM_LOC    "No se puede confirmar la nueva contraseña. Vuelva a intentarlo."
#DEFINE NOPSWDENTERED_LOC	"No ha escrito la contraseña anterior. ¿Desea continuar?"
#DEFINE FILESAVEDAS_LOC		"Archivo guardado como"
#DEFINE VALIDATING_LOC      "Validando ..."
#DEFINE PRINTING_LOC        "Imprimir ..."
#DEFINE METHOD_LOC          "Método:"
#DEFINE LINENUM_LOC			"Línea:"
#DEFINE CUSTNOORD_LOC		"El cliente no tiene pedidos."
#DEFINE SELCUSTFIRST_LOC    "Primero debe seleccionar un cliente."
#DEFINE NOEMPLOYEES_LOC		"No hay empleados en el archivo."

*-- Other strings
#DEFINE SELECTBUTTON_LOC    "Seleccionar"
#DEFINE COPYRIGHT_LOC		"Copyright 1996 Microsoft Corporation"
#DEFINE RIGHTSRSRVD_LOC		"Reservados todos los derechos"
#DEFINE ABOUT_LOC			"Acerca de "
#DEFINE VERSIONLABEL_LOC    "Versión "
