            SET BELL TO 512,1
            ??CHR(7)
            SET BELL TO 800,1
            ??CHR(7)
            SET BELL TO 200,1
            ??CHR(7)
            SET BELL TO 1000,1
            ??CHR(7)
            SET BELL TO 100,1
            ??CHR(7)
            SET BELL TO 2500,1
            ??CHR(7)
            SET BELL TO 50,1
            ??CHR(7)
            SET BELL TO 512,1
            ??CHR(7)
            SET BELL TO 800,1
            ??CHR(7)
            SET BELL TO 200,1
            ??CHR(7)
            SET BELL TO 1000,1
            ??CHR(7)
            SET BELL TO 100,1
            ??CHR(7)
            SET BELL TO 2500,1
            ??CHR(7)
            SET BELL TO 50,1
            ??CHR(7)
